#!/bin/bash

if [ -d "$1/000" ]; then
    cd "$1"
else
    echo "This script chmod's a 000..999 folder structure. Files are chmod'ed to 666 and directories to 777"
    echo "Usage: $0 [folder where 000..999 tree exists]"
    exit
fi

for i in `seq -f%03g 0 999`;
do
    chmod 666 ./$i/*
    chmod 777 ./$i
done

