#!/bin/bash

if [ `whoami` != "root" ]; then
    echo
    echo ERROR: This script must run as root
    echo
else
    base="/var/www/html/p"
    for k in `seq -f%01g 0 6`; do
        for i in `seq -f%03g 0 999`; do
            if [ "$(ls -A $base$k/$i)" ]; then
                echo $base$k/$i
                chown dvdaf.dvdaf $base$k/$i/*
                chmod 666 $base$k/$i/*
            fi
        done
    done

    base="/var/www/html/o"
    for k in `seq -f%01g 0 6`; do
        for i in `seq -f%03g 0 999`; do
            if [ "$(ls -A $base$k/$i)" ]; then
                echo $base$k/$i
                chown dvdaf.dvdaf $base$k/$i/*
                chmod 666 $base$k/$i/*
            fi
        done
    done
fi

