#!/bin/bash

#p0/###    small                *.gif +++ already populated
#p1/###    medium               *.jpg --- to be populated
#p2/###    large                *.jpg -
#p3/###    huge                 *.jpg -
#p4/###    original display     *.jpg --- to be populated
#p5/###    edited               *.pgn
#p6/###    original             *.jpg +++
#uploads   unprocessed pics     *.jpg, *.gif, *.bmp, *.png

function echo_usage {
    echo ""
    echo "This script will move '/var/www/html/p_/___/[source].* to '/var/www/html/o_/___/[source]-[timestamp].*' for p0, p1, p2, p3, p5 and p6."
    echo ""
    if [ "$1" != '' ]; then
	echo "ERROR:"
	echo "    $1"
	echo ""
    fi
    echo "Usage:"
    echo "    $0 [source] [timestamp]"
    echo ""
    echo "Source:"
    echo "    File name without an extension for '/var/www/html/p_/___/[source].*', no path"
    echo ""
    echo "Timestamp:"
    echo "    Timestamp to append to [source]"
    echo ""
    exit
}

#get source "009000-d0"
dir="${1:3:3}"
srn="$1"
src="/var/www/html/p6/$dir/$srn.jpg"
if [ ! -f "$src" ]; then
    echo_usage "Could not find source file $src"
fi
shift

#get timestamp
stp="$1"
if [ "$stp" = "" ]; then
    echo_usage "Missing timestamp $stp"
fi
shift

mv -f "/var/www/html/p0/$dir/$srn.gif" "/var/www/html/o0/$dir/$srn.$stp.gif" 2> /dev/null
mv -f "/var/www/html/p1/$dir/$srn.jpg" "/var/www/html/o1/$dir/$srn.$stp.jpg" 2> /dev/null
mv -f "/var/www/html/p2/$dir/$srn.jpg" "/var/www/html/o2/$dir/$srn.$stp.jpg" 2> /dev/null
mv -f "/var/www/html/p3/$dir/$srn.jpg" "/var/www/html/o3/$dir/$srn.$stp.jpg" 2> /dev/null
mv -f "/var/www/html/p4/$dir/$srn.jpg" "/var/www/html/o4/$dir/$srn.$stp.jpg" 2> /dev/null
mv -f "/var/www/html/p5/$dir/$srn.jpg" "/var/www/html/o5/$dir/$srn.$stp.jpg" 2> /dev/null
mv -f "/var/www/html/p6/$dir/$srn.jpg" "/var/www/html/o6/$dir/$srn.$stp.jpg" 2> /dev/null

chmod 666 "/var/www/html/o0/$dir/$srn.$stp.gif" 2> /dev/null
chmod 666 "/var/www/html/o1/$dir/$srn.$stp.jpg" 2> /dev/null
chmod 666 "/var/www/html/o2/$dir/$srn.$stp.jpg" 2> /dev/null
chmod 666 "/var/www/html/o3/$dir/$srn.$stp.jpg" 2> /dev/null
chmod 666 "/var/www/html/o4/$dir/$srn.$stp.jpg" 2> /dev/null
chmod 666 "/var/www/html/o5/$dir/$srn.$stp.jpg" 2> /dev/null
chmod 666 "/var/www/html/o6/$dir/$srn.$stp.jpg" 2> /dev/null

