#!/bin/bash

for k in `seq -f%01g 0 0`;
do
    for i in `seq -f%03g 0 999`;
    do
	cd /var/www/html/p$k/$i
	pwd
	for j in `ls *.gif | awk --field-separator . '{print substr($0,3,6)}'`
	do
	    mv d-${j}-0.gif ${j}-d0.gif
	done
    done
done

