#!/bin/bash

#p0/###    small                *.gif +++ already populated
#p1/###    medium               *.jpg --- to be populated
#p2/###    large                *.jpg -
#p3/###    huge                 *.jpg -
#p4/###    original display     *.jpg --- to be populated
#p5/###    edited               *.pgn
#p6/###    original             *.jpg +++
#uploads   unprocessed pics     *.jpg, *.gif, *.bmp, *.png

function echo_usage {
    echo ""
    echo "This script will copy '/var/www/html/p_/___/[source].* to '/var/www/html/o_/___/[source].[version]-[sub-version].*' for p0, p1, p2, p3, p5 and optionally p6."
    echo ""
    if [ "$1" != '' ]; then
	echo "ERROR:"
	echo "    $1"
	echo ""
    fi
    echo "Usage:"
    echo "    $0 [source] [version] [sub-version] [newpic]"
    echo ""
    echo "Source:"
    echo "    File name without an extension for '/var/www/html/p_/___/[source].*', no path"
    echo ""
    echo "version:"
    echo "    Version number to append to [source]"
    echo ""
    echo "sub-version:"
    echo "    Sub-version number to append to [source], If sub-version is 0 we also copy p6"
    echo ""
    echo "newpic"
    echo "    If newpic is present p6 will be copied"
    echo ""
    exit
}

function copy-version {
    if [ "$1" != "" ]; then
	if [ -f "$1" ]; then
	    if [ "$2" != "" ]; then
		cp -f $1 $2
		chmod 666 $2 2> /dev/null
	    else
		echo "Usage: copy-version [source] [target]"
	    fi
	fi
    else
	echo "Usage: copy-version [source] [target]"
    fi
}

#get source "009000-d0"
dir="${1:3:3}"
srn="$1"
src="/var/www/html/p6/$dir/$srn.jpg"
if [ ! -f "$src" ]; then
    echo_usage "Could not find source file $src"
fi
shift

#get version
ver="$1"
if [ "$ver" = "0" -o "$ver" -gt 0 ]; then
	ver="$ver"
    else
	echo_usage "Invalid version $ver"
fi
shift

#get sub-version
sub="$1"
if [ "$sub" = "0" -o "$sub" -gt 0 ]; then
	sub="$sub"
    else
	echo_usage "Invalid sub-version $sub"
fi
shift

#get sub-version
newpic="$1"

copy-version "/var/www/html/p0/$dir/$srn.gif" "/var/www/html/o0/$dir/$srn.$ver-$sub.gif"
copy-version "/var/www/html/p1/$dir/$srn.jpg" "/var/www/html/o1/$dir/$srn.$ver-$sub.jpg"
copy-version "/var/www/html/p2/$dir/$srn.jpg" "/var/www/html/o2/$dir/$srn.$ver-$sub.jpg"
copy-version "/var/www/html/p3/$dir/$srn.jpg" "/var/www/html/o3/$dir/$srn.$ver-$sub.jpg"
copy-version "/var/www/html/p5/$dir/$srn.jpg" "/var/www/html/o5/$dir/$srn.$ver-$sub.jpg"
chmod 666 "/var/www/html/o0/$dir/$srn.$ver-$sub.gif" 2> /dev/null
chmod 666 "/var/www/html/o1/$dir/$srn.$ver-$sub.jpg" 2> /dev/null
chmod 666 "/var/www/html/o2/$dir/$srn.$ver-$sub.jpg" 2> /dev/null
chmod 666 "/var/www/html/o3/$dir/$srn.$ver-$sub.jpg" 2> /dev/null
chmod 666 "/var/www/html/o5/$dir/$srn.$ver-$sub.jpg" 2> /dev/null

if [ "$newpic" = "1" ]; then
    copy-version "/var/www/html/p6/$dir/$srn.jpg" "/var/www/html/o6/$dir/$srn.$ver-0.jpg"
    chmod 666 "/var/www/html/o6/$dir/$srn.$ver-0.jpg" 2> /dev/null
fi

