#!/bin/bash

function echo_usage {
    echo ""
    echo "This script will apply a series of transformations to [source] and save it to [target]. If the traget is a jpg the quality will be 90."
    echo ""
    if [ "$1" != '' ]; then
	echo "ERROR:"
	echo "    $1"
	echo ""
    fi
    echo "Usage:"
    echo "    $0 [source] [target] transform instructions..."
    echo ""
    echo "Source:"
    echo "    Source full filename including path and extension"
    echo ""
    echo "Target:"
    echo "    Target full filename including path and extension"
    echo ""
    echo "Transform instructions"
    echo "    autocrop [0..100]"
    echo "    rotate [0..360]"
    echo "    crop_x1 [1..]"
    echo "    crop_x2 [1..]"
    echo "    crop_y1 [1..]"
    echo "    crop_y2 [1..]"
    echo "    black [0..100]"
    echo "    white [0..100]"
    echo "    gamma [0..3]"
    echo "    restore"
    echo ""
    exit
}

function get_int {
    echo `echo "$1" | sed -n '/^-\?[0-9]\+$/p'`
}

function get_float {
    echo `echo "$1" | sed -n '/^-\?[0-9]\+\(\.[0-9]*\)\?$/p'`
}

#get source
src="$1"
if [ ! -f "$src" ]; then
    echo_usage "$src not found."
fi
shift

#get target
ext=$[${#1}-3]
ext="${1:$ext:3}"
trg="$1"
if [ "$trg" = "" ]; then
    echo_usage "Target file not specified."
fi
shift

#generate transform
autocrop=''
rotate=''
crop_x1=''
crop_x2=''
crop_y1=''
crop_y2=''
black=''
white=''
gamma=''
restore=''
while [ "$#" -gt 0 ]; do
    case "$1" in
    "autocrop") autocrop=`get_int "$2"`; shift; ;;
    "rotate"  ) rotate=`get_float "$2"`; shift; ;;
    "crop_x1" ) crop_x1=`get_int "$2"` ; shift; ;;
    "crop_x2" ) crop_x2=`get_int "$2"` ; shift; ;;
    "crop_y1" ) crop_y1=`get_int "$2"` ; shift; ;;
    "crop_y2" ) crop_y2=`get_int "$2"` ; shift; ;;
    "black"   ) black=`get_int "$2"`   ; shift; ;;
    "white"   ) white=`get_int "$2"`   ; shift; ;;
    "gamma"   ) gamma=`get_float "$2"` ; shift; ;;
    "restore" ) restore="1";                    ;;
    *         ) echo_usage "$1 is an unknown transform parameter"; ;;
    esac
    shift
done

if [ "$restore" != "" ]; then
    echo "retore image"
    exit
fi

#echo "autocrop = $autocrop"
#echo "rotate = $rotate"
#echo "crop_x1 = $crop_x1"
#echo "crop_x2 = $crop_x2"
#echo "crop_y1 = $crop_y1"
#echo "crop_y2 = $crop_y2"
#echo "black = $black"
#echo "white = $white"
#echo "gamma = $gamma"
#echo "restore = $restore"

c1='' #convert
if [ "$autocrop" != "" ]; then
    c1="-fuzz ${autocrop}% -trim +repage"
fi

c2='' #convert
if [ "$rotate" != "" ]; then
    c=`echo "scale=10; x=${rotate}; x=c(x*4*a(1)/180); if ( x > 0 ) x+=0.0000000005 else x-=0.0000000005;  x/10*10" | bc -l`
    s=`echo "scale=10; x=${rotate}; x=s(x*4*a(1)/180); if ( x > 0 ) x+=0.0000000005 else x-=0.0000000005;  x/10*10" | bc -l`
    z=`echo "scale=10; x=${rotate}; x=s(x*4*a(1)/180); if ( x > 0 ) x+=0.0000000005 else x-=0.0000000005; -x/10*10" | bc -l`
    c2="-affine ${c},${s},${z},${c},0,0 -transform +repage"
fi

c3='' #convert
if [ "$crop_x1" != "" ]; then
    if [ "$crop_y1" != "" ]; then
	c3="-crop +${crop_x1}+${crop_y1}"
    else
	c3="-crop +${crop_x1}+0"
    fi
else
    if [ "$crop_y1" != "" ]; then
	c3="-crop +0+${crop_y1}"
    fi
fi

c4='' #convert
if [ "$crop_x2" != "" ]; then
    if [ "$crop_y2" != "" ]; then
	c4="-crop -${crop_x2}-${crop_y2}"
    else
	c4="-crop -${crop_x2}-0"
    fi
else
    if [ "$crop_y2" != "" ]; then
	c4="-crop -0-${crop_y2}"
    fi
fi

c5='' #convert
if [ "$black" != "" ]; then
    if [ "$white" != "" ]; then
	if [ "$gamma" != "" ]; then
	    c5="-level ${black}%,${white}%,${gamma}"
	else
	    c5="-level ${black}%,${white}%"
	fi
    else
	if [ "$gamma" != "" ]; then
	    c5="-level ${black}%,100%,${gamma}"
	else
	    c5="-level ${black}%,100%"
	fi
    fi
else
    if [ "$white" != "" ]; then
	if [ "$gamma" != "" ]; then
	    c5="-level 0%,${white}%,${gamma}"
	else
	    c5="-level 0%,${white}%"
	fi
    else
	if [ "$gamma" != "" ]; then
	    c5="-gamma ${gamma}"
	fi
    fi
fi

cmd=''
if [ "$c1" != "" ]; then if [ "$cmd" != "" ]; then cmd="$cmd miff:- | convert - $c1"; else cmd="$c1"; fi fi
if [ "$c2" != "" ]; then if [ "$cmd" != "" ]; then cmd="$cmd miff:- | convert - $c2"; else cmd="$c2"; fi fi
if [ "$c3" != "" ]; then if [ "$cmd" != "" ]; then cmd="$cmd miff:- | convert - $c3"; else cmd="$c3"; fi fi
if [ "$c4" != "" ]; then if [ "$cmd" != "" ]; then cmd="$cmd miff:- | convert - $c4"; else cmd="$c4"; fi fi
if [ "$c5" != "" ]; then if [ "$cmd" != "" ]; then cmd="$cmd miff:- | convert - $c5"; else cmd="$c5"; fi fi

qual=''
if [ "$ext" = "jpg" ]; then
    qual="-quality 90"
fi

#echo "convert $src $cmd $qual $trg" >> /var/www/html/uploads/zz.log
eval "convert $src $cmd $qual $trg"

